### ISSUE TITLE
Unable to load custom book.

### ISSUE THREAD

**Issue by baka-gourd** [Vazkii/Patchouli#114] opened 2019-03-12 14:53 UTC
### Default language:Chinese
Unable to load custom book.
**Has been restarted and reloaded many times.**
May be the system cause:D
![2019-03-12 22-47-27 的屏幕截图](https://user-images.githubusercontent.com/36119339/54209537-ea109e00-4518-11e9-8aff-147611a0fbf1.png)
![2019-03-12 22-47-48 的屏幕截图](https://user-images.githubusercontent.com/36119339/54209590-044a7c00-4519-11e9-9458-4d59c31203d8.png)

**Comment by Ellpeck** [comment] 2019-03-12 15:08
Duplicate of #115

**Closed by Ellpeck** 2019-03-12 15:08 UTC
