### ISSUE TITLE
Patchouli Books Unreadable

### ISSUE THREAD

**Issue by doctor-something5000** [Vazkii/Patchouli#264] opened 2020-07-01 13:34 UTC
Hi, I have opened this issue for the developers  to notice a problem which I am currently facing.
The Patchouli books which are added by the mods: **PneumaticCraft: Repressurized** and **Alchemistry mod** are unfortunately **unreadable**; only _vertical rectangles_ are seen. This makes it **impossible** to know what's happening and **more importantly difficult to progress within the mod**.
I really hope that this Issue be reviewed and fixed right away as **am having difficulties in progressing the two mods** mentioned above offline.
With Regards,

 _A user of your great mod_
P.S. If you require files that you may request like _logs_, I am happy to present them.

**Comment by williewillus** [comment] 2020-07-01 15:56
Duplicate of #236

**Closed by williewillus** 2020-07-01 15:56 UTC
